<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/26 0026
 * Time: 16:52
 */

namespace frontend\controllers;


use common\helpers\CommonHelpers;
use frontend\assets\AppAsset;
use yii\db\ActiveRecord;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;

class BaseController extends Controller
{
    public $enableCsrfValidation = false;
    public $_userInfo = [];
    public $uid = null;
    const POST = 'POST';
    const GET = 'GET';

    function init()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        if (!\Yii::$app->user->isGuest){
            $this->_userInfo = [
                'uid'=>\Yii::$app->user->identity->getId(),
                'username'=>\Yii::$app->user->identity->username,
                'status'=>\Yii::$app->user->identity->status,
            ];
            $this->uid = $this->_userInfo['uid'];
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

   function behaviors()
   {
       return [
           'verbs' => [
               'class' => VerbFilter::className(),
           ],
           'access' => [
               'class' => \yii\filters\AccessControl::className(),
//                'only' => [],
               'rules' => [
                   [
                       'allow' => true,// 设置 actions 的操作是允许访问还是拒绝访问
                       'roles' => ['@'], // @ 当前规则针对认证过的用户， ？所有用户均可访问
//                        'ips' => ['127.0.0.1'],//这里填写允许访问的IP
//                       'actions'=>[], // 当前 rule 将会针对这里设置的 actions 起作用，如果为空，则默认对当前 controller 的所actions 起作用
                   ],
               ],
               'denyCallback'=>function($rule,$action){//被拒绝后的回调
                   echo json_encode([
                       'code'=>0,
                       'msg'=>'请登录后操作'
                   ]);
               },
           ]
       ];
   }

    function _getUid(){
        if (!\Yii::$app->user->isGuest){
            return \Yii::$app->user->getId();
        }
        return null;
    }

    function actionLogout()
    {
        \Yii::$app->user->logout(true);
    }
}