<?php
/**
 * Created by PhpStorm.
 * User: weilone
 * Date: 2020/7/4
 * Time: 16:33
 */

namespace frontend\controllers;


use common\models\Options;
use yii\web\Controller;
use yii\web\Response;

class BaseController extends Controller
{

    private $needLogin = [
        'news' => [
            'index',
        ]
    ];

    public function behaviors()
    {
        return [];
    }

    public function beforeAction($action)
    {
        if (!isset($this->needLogin[$this->action->controller->id][$this->action->id])) {
            if (!\Yii::$app->getUser()->getIsGuest()) {
                return $this->goHome();
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 获取banner
     * @return array
     */
    public function actionBanner()
    {
        $type = \Yii::$app->request->get('type', 'index');
        $info = Options::findOne(['name' => $type]);
        $data = [];
        if ($info) {
            $data = \Qiniu\json_decode($info->value, true);
        }
        return $this->outPut($data);
    }

    public function outPut($data = [], $code = 1, $msg = 'success')
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return [
            'data' => $data,
            'code' => $code,
            'msg' => $msg
        ];
    }
}