<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/26 0026
 * Time: 16:53
 */

namespace frontend\controllers;

use Yii;
use frontend\models\form\SignupForm;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use common\models\LoginForm;
use common\models\doctors\DoctorHospitals;
use common\models\doctors\DoctorInfos;
use common\models\doctors\DoctorPatients;
use frontend\models\User;

class IndexController extends BaseController
{

    function init()
    {
        parent::init();
    }

    function actionIndex()
    {
        return [
            'code'=>1,
            'msg'=>'',
            'data'=>DoctorInfos::findAll()
        ];
    }

    function behaviors()
    {
        $be = parent::behaviors(); // TODO: Change the autogenerated stub
        return ArrayHelper::merge($be, [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'login' => ['POST'],
                    'register' => ['POST'],
                    'submit_info' => ['POST'],
                    'create_patient' => ['POST'],
                    'transfer_patient' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['submit_info', 'create_patient', 'transfer_patient', 'transfer_patient_list', 'patient_detail', 'my_patient_list'],
                'rules' => [
                    [
//                        'ips' => ['127.0.0.1'],//这里填写允许访问的IP
                        'allow' => !Yii::$app->user->isGuest,
                    ],
                ]
            ]
        ]);
    }

    /**
     * password username
     * @return array
     * @throws \Throwable
     */
    function actionLogin()
    {
        if (!hasLogin()) {
            $model = new LoginForm();
            $model->username = Yii::$app->request->post('tel');
            $model->password = Yii::$app->request->post('password');
            if (!$model->login()) {
                return [
                    'code' => 0,
                    'msg' => '账号或密码错误'
                ];
            }
        }
        return [
            'data' => Yii::$app->user->identity,
            'code' => 0,
            'msg' => ''
        ];
    }

    function actionRegister()
    {
        $username = Yii::$app->request->post('tel');
        $password = Yii::$app->request->post('password');

        if (User::findOne(['username' => $username])) {
            return [
                'code' => 0,
                'msg' => '改账号已被注册'
            ];
        } else {
            $user = new SignupForm();
            $user->username = $username;
            $user->password = $password;
            $user->email = $username.'@qq.com';

            if ($user->signup()) {
                return [
                    'data' => $user,
                    'code' => 1,
                    'msg' => '注册成功'
                ];
            } else {
                return [
                    'code' => 0,
                    'msg' => '注册失败，请检查参数'
                ];
            }
        }
    }


    /**
     * 完善信息表单
     * Parma:{name,doctor_type,role,hospital_location,hospital_name,certificate(base64)}
     */
    function actionSubmit_info()
    {
        $_post = Yii::$app->request->post();
        if ($res = $this->_setValForObj(new DoctorInfos(), $_post)) {
            $hospital = new DoctorHospitals();
            $hospital->name = $res->hospital_name;
            $hospital->address = $res->hospital_location;
            $hospital->save();
            $res->hospital_id = $hospital->id;
            $res->uid = $this->_getUid();
            $this->_save($res);
            return [
                'data' => $res->toArray(),
                'code' => 1,
                'msg' => 'succ'
            ];
        }
        return [
            'code' => 0,
            'msg' => 'error'
        ];
    }

    /**
     * 创建病人
     * @return array
     */
    function actionCreate_patient()
    {
        $_post = Yii::$app->request->post();
        $_post['doctor_id'] = $this->_getUid();
        $_post['hospital_id'] = DoctorInfos::getHospitalIdByUid($_post['doctor_id']);
        if ($res = $this->_setValForObj(new DoctorPatients(), $_post, true)) {
            return [
                'data' => $res->toArray(),
                'code' => 1,
                'msg' => 'succ'
            ];
        }
        return [
            'code' => 0,
            'msg' => 'error'
        ];
    }

    /**
     * 转移病人
     * @return array
     */
    function actionTransfer_patient()
    {
        $_post = Yii::$app->request->post();
        if (!$_post['patient_id'] || $_post['hospital_id']) {
            return [
                'code' => 0,
                'msg' => '参数错误'
            ];
        }
        $patient = DoctorPatients::findOne(['id' => $_post['patient_id']]);
//        $patient->is_transfer = 0;
        $patient->hospital_id = $_post['hospital_id'];
        $patient->doctor_id = 0;
        if ($patient->update()) {
            return [
                'data' => $patient->toArray(),
                'code' => 1,
                'msg' => 'succ'
            ];
        }
        return [
            'code' => 0,
            'msg' => 'error'
        ];
    }

    function actionMy_patient_list(){
        return [
            'data' => DoctorPatients::getPatientsByDoctorId($this->_getUid())->toArray(),
            'code' => 1,
            'msg' => ''
        ];
    }

    /**
     *转给我的病人
     */
    function actionTransfer_patient_list()
    {
        return [
            'data' => DoctorPatients::getPatientsByDoctorId($this->_getUid(),true)->toArray(),
            'code' => 1,
            'msg' => ''
        ];
    }

    /**
     * 病人明细
     * @return array
     */
    function actionPatient_detail()
    {
        $Patient_id = Yii::$app->request->get('patient_id');
        return [
            'data' => DoctorPatients::findOne(['id' => $Patient_id])->toArray(),
            'code' => 1,
            'msg' => ''
        ];
    }

    /**
     * 医院搜索
     * @return array
     */
    function actionSearch_hospital()
    {
        $search_word = Yii::$app->request->get('search_word');
        return [
            'data'=>DoctorHospitals::like('name',$search_word)
        ];
    }

    function actionGetmy(){
        return $this->_userInfo;
    }
}