<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/26 0026
 * Time: 16:53
 */

namespace frontend\controllers;

use Yii;
use frontend\models\form\SignupForm;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use common\models\LoginForm;
use common\models\doctors\DoctorHospitals;
use common\models\doctors\DoctorInfos;
use common\models\doctors\DoctorPatients;
use frontend\models\User;

class IndexController extends BaseController
{

    function init()
    {
        parent::init();
    }

    function actionIndex()
    {
        return [
            'code'=>1,
            'msg'=>'',
            'doctors'=>DoctorInfos::findAll(),
            'users'=>User::find()->select('*')->all()
        ];
    }

    function behaviors()
    {
        $be = parent::behaviors(); // TODO: Change the autogenerated stub
        return ArrayHelper::merge($be, [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'login' => ['POST'],
                    'register' => ['POST'],
                    'submit_info' => ['POST'],
                    'create_patient' => ['POST'],
                    'transfer_patient' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['submit_info', 'create_patient', 'transfer_patient', 'transfer_patient_list', 'patient_detail', 'my_patient_list','getme'],
                'rules' => [
                    [
                        'allow' => true,// 设置 actions 的操作是允许访问还是拒绝访问
                        'roles' => ['@'], // @ 当前规则针对认证过的用户， ？所有用户均可访问
//                        'ips' => ['127.0.0.1'],//这里填写允许访问的IP
//                        'actions'=>['logout'], // 当前 rule 将会针对这里设置的 actions 起作用，如果为空，则默认对当前 controller 的所actions 起作用
                    ],
                ],
                'denyCallback'=>function($rule,$action){//被拒绝后的回调

                },
            ]
        ]);
    }

    /**
     * password username
     * @return array
     * @throws \Throwable
     */
    function actionLogin()
    {
        if (!hasLogin()) {
            $model = new LoginForm();
            $model->username = Yii::$app->request->post('tel');
            $model->password = Yii::$app->request->post('password');
            if (!$model->login()) {
                return [
                    'code' => 0,
                    'msg' => '账号或密码错误'
                ];
            }
        }
        return [
            'data' => ArrayHelper::merge(['is_complete'=>$this->getDoctor()],Yii::$app->user->identity),
            'code' => 1,
            'msg' => ''
        ];
    }

    function actionRegister()
    {
        $username = Yii::$app->request->post('tel');
        $password = Yii::$app->request->post('password');

        if (User::findOne(['username' => $username])) {
            return [
                'code' => 0,
                'msg' => '改账号已被注册'
            ];
        } else {
            $user = new SignupForm();
            $user->username = $username;
            $user->password = $password;
            $user->email = $username.'@qq.com';

            if ($user->signup()) {
                $model = new LoginForm();
                $model->username = $username;
                $model->password = $password;
                $model->login();
                return [
                    'data' => ArrayHelper::merge(['is_complete'=>$this->getDoctor()],Yii::$app->user->identity),
                    'code' => 1,
                    'msg' => '注册成功',

                ];
            } else {
                return [
                    'code' => 0,
                    'msg' => '注册失败，请检查参数'
                ];
            }
        }
    }


    /**
     * 完善信息表单
     * Parma:{name,doctor_type,role,hospital_location,hospital_name,certificate(base64)}
     */
    function actionSubmit_info()
    {
        $_post = Yii::$app->request->post();
        if ($res = $this->_setValForObj(new DoctorInfos(), $_post)) {
            $hospital = new DoctorHospitals();
            $hospital->name = $res->hospital_name;
            $hospital->address = $res->hospital_location;
            $hospital->save();
            $res->hospital_id = $hospital->id;
            $res->uid = $this->_getUid();
            $this->_save($res);
            return [
                'data' => $res->toArray(),
                'code' => 1,
                'msg' => 'succ'
            ];
        }
        return [
            'code' => 0,
            'msg' => 'error'
        ];
    }

    /**
     * 创建病人
     * @return array
     */
    function actionCreate_patient()
    {
        $_post = Yii::$app->request->post();
        $_post['doctor_id'] = $this->_getUid();
        $_post['hospital_id'] = DoctorInfos::getHospitalIdByUid($_post['doctor_id']);
        if ($_post['hospital_id'] && ($res = $this->_setValForObj(new DoctorPatients(), $_post, true))) {
            return [
                'data' => $res->toArray(),
                'code' => 1,
                'msg' => 'succ'
            ];
        }
        return [
            'code' => 0,
            'msg' => '参数错误'
        ];
    }

    /**
     * 转移病人
     * @return array
     */
    function actionTransfer_patient()
    {
        $_post = Yii::$app->request->post();
        if (!$_post['patient_id'] || $_post['hospital_id']) {
            return [
                'code' => 0,
                'msg' => '参数错误'
            ];
        }
        $patient = DoctorPatients::findOne(['id' => $_post['patient_id']]);
//        $patient->is_transfer = 0;
        $patient->hospital_id = $_post['hospital_id'];
        $patient->doctor_id = 0;
        if ($patient->update()) {
            return [
                'data' => $patient->toArray(),
                'code' => 1,
                'msg' => 'succ'
            ];
        }
        return [
            'code' => 0,
            'msg' => 'error'
        ];
    }

    function actionMy_patient_list(){
        return [
            'data' => DoctorPatients::getPatientsByDoctorId($this->_getUid()),
            'code' => 1,
            'msg' => ''
        ];
    }

    /**
     *转给我的病人
     */
    function actionTransfer_patient_list()
    {
        return [
            'data' => DoctorPatients::getPatientsByDoctorId($this->_getUid(),true),
            'code' => 1,
            'msg' => ''
        ];
    }

    /**
     * 病人明细
     * @return array
     */
    function actionPatient_detail()
    {
        $Patient_id = Yii::$app->request->get('patient_id');
        return [
            'data' => DoctorPatients::findOne(['id' => $Patient_id]),
            'code' => 1,
            'msg' => ''
        ];
    }

    /**
     * 医院搜索
     * @return array
     */
    function actionSearch_hospital()
    {
        $search_word = Yii::$app->request->get('search_word');
        return [
            'data'=>DoctorHospitals::like('name',$search_word)
        ];
    }

    function actionGetme(){
        return ArrayHelper::merge(['is_complete'=>$this->getDoctor()],Yii::$app->user->identity);
    }

    function getDoctor($uid=''){
        if (!$uid){
            $uid = Yii::$app->user->getId();
        }
        $info = DoctorInfos::findOne(['uid'=>$uid]);
        return !is_array($info) ? [] : $info;
    }
}