<?php
/**
 * Author: lf
 * Blog: https://blog.feehi.com
 * Email: job@feehi.com
 * Created at: 2017-03-15 21:16
 */

namespace backend\models;

use common\models\doctors\DoctorHospitals;
use Yii;
use backend\components\CustomLog;
use common\helpers\Util;
use yii\base\Event;
use yii\web\ForbiddenHttpException;

class DadminUser extends User
{

    protected $name_fix = 'hospital_';
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password', 'repassword', 'password_hash'], 'string'],
            ['email', 'email'],
            ['email', 'unique'],
            [['repassword'], 'compare', 'compareAttribute' => 'password'],
            [['avatar'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, gif, webp'],
            [['status'], 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
            [['username', 'password', 'repassword'], 'required', 'on' => ['create']],//'email',
            [['username'], 'required', 'on' => ['update', 'self-update']],//, 'email'
            [['username'], 'unique', 'on' => 'create'],
            [['roles', 'permissions'], 'safe'],
        ];
    }

    function getHospital(){
        return $this->hasOne(DoctorHospitals::className(),['id'=>'hospital_id']);
    }

    function beforeSave($insert)
    {
//        $this->username = $this->name_fix.$this->username;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}

