<?php
/**
 * Author: lf
 * Blog: https://blog.feehi.com
 * Email: job@feehi.com
 * Created at: 2017-03-15 21:16
 */

namespace backend\models;

use common\models\doctors\DoctorHospitals;
use Yii;
use backend\components\CustomLog;
use common\helpers\Util;
use yii\base\Event;
use yii\web\ForbiddenHttpException;

/**
 * DadminUser model
 *
 * @property string $hospital_id
 * @property string $job_number
 */

class DadminUser extends User
{

    protected $name_fix = 'hospital_';
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password', 'repassword', 'password_hash','job_number'], 'string'],
            ['hospital_id', 'integer'],
            ['email', 'email'],
            ['email', 'unique'],
            [['repassword'], 'compare', 'compareAttribute' => 'password'],
            [['avatar'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, gif, webp'],
            [['status'], 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
            [['username', 'password', 'repassword'], 'required', 'on' => ['create']],//'email',
            [['username'], 'required', 'on' => ['update', 'self-update']],//, 'email'
            [['username'], 'unique', 'on' => 'create'],
            [['roles', 'permissions'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'username' => Yii::t('app', 'Username'),
            'hospital_id' => '所属医院ID',
            'job_number' => '工号',
            'email' => Yii::t('app', 'Email'),
            'old_password' => Yii::t('app', 'Old Password'),
            'password' => Yii::t('app', 'Password'),
            'repassword' => Yii::t('app', 'Repeat Password'),
            'avatar' => Yii::t('app', 'Avatar'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At')
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        return [
            'default' => ['username', 'email'],
            'create' => ['username', 'email', 'password', 'avatar', 'status', 'roles', 'permissions','hospital_id','job_number'],
            'update' => ['username', 'email', 'password', 'avatar', 'status', 'roles', 'permissions','hospital_id','job_number'],
            'self-update' => ['email', 'password', 'avatar', 'old_password', 'repassword'],
        ];
    }

    function getHospital(){
        return $this->hasOne(DoctorHospitals::className(),['id'=>'hospital_id']);
    }

    function beforeSave($insert)
    {
//        $this->username = $this->name_fix.$this->username;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}

