<?php
/**
 * Created by PhpStorm.
 * User: weilone
 * Date: 2018/12/27
 * Time: 22:34
 */

namespace frontend\models;

use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class DoctorPatients extends ActiveRecord
{

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    static function tableName()
    {
        return '{{%doctor_patients}}'; // TODO: Change the autogenerated stub
    }

    static function getPatientsByDoctorId($DoctorId,$is_transfer = false)
    {
        if ($is_transfer){
             return self::findAll(['doctor_id' => $DoctorId,'is_transfer'=>1]);
        }
        return self::findAll(['doctor_id' => $DoctorId]);
    }
}