<?php
/**
 * Created by PhpStorm.
 * User: weilone
 * Date: 2018/12/27
 * Time: 22:06
 */

namespace frontend\models;


use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class DoctorHospitals extends ActiveRecord
{

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    static function tableName()
    {
        return '{{%doctor_hospitals}}'; // TODO: Change the autogenerated stub
    }

    static function like($coloum,$value){
        return self::find()->where($coloum.' like "%'.$value.'%"')->all();
    }
}